### ISSUE TITLE
ansible-zogpool

### ISSUE THREAD

**Issue by igorwhite** [Zogpool/ansible-zogpool#1]
Hello!
How to run an extension .yml ubuntu 16.04?
What do I need to install dependencies?

Best Regards.

**Comment by igorwhite** [comment]
Sorry 
I understood!
sudo apt-get install ansible
Now I have another error:
SUDO password:
 [WARNING]: provided hosts list is empty, only localhost is available

[DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and make sure become_method is 'sudo' (default). This feature will be removed in a
future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

PLAY [Install Zcash pool software] *********************************************
skipping: no hosts matched

PLAY RECAP *********************************************************************

**Comment by omaralvarez** [comment]
You need to install and know how to use ansible. You need to tell ansible the IPs of your server or servers. 

http://docs.ansible.com/ansible/intro_inventory.html
